### ISSUE TITLE
Crash on startup while trying to read saves

### ISSUE THREAD

**Issue by RudelNudel** [tylercamp/palcalc#12]
[CRASHLOG.zip](https://github.com/tylercamp/palcalc/files/15254525/CRASHLOG.zip)

Hi,
Upon starting the program it crashes while trying to read the saves. No mods on the Steam version installed.
Version 0.8 runs fine.

**Comment by tylercamp** [comment]
@RudelNudel Can you send a full copy of your save game folder? I'm able to reproduce the crash with the files in the ZIP you sent, same underlying issue as #11. Though in your case it's a single female Foxparks, lv 6 with `Insulated Body` in slot 1 of a container that has appeared out of the aether

I'd ask if you could find it somewhere but you have way too many pals for that

I'm wondering if this has to do with butchered pals, have you done that on your save?

**Comment by RudelNudel** [comment]
I've played since then but i will get you the whole savefolder once I'll get back at the pc. Though that will be tomorrow.
I have never butchered a pal so far. Haven't even researched it.

**Comment by RudelNudel** [comment]
[CRASHLOG.zip](https://github.com/tylercamp/palcalc/files/15256119/CRASHLOG.zip)

here the new crashlog.zip in case me playing the game changed something.
the savegames folder is way to big to send it with github. uploaded it here: https://drive.google.com/file/d/1aYXlbTwmtvELvbLP7YrtyCRv4b2ZhNR3/view?usp=sharing

**Comment by tylercamp** [comment]
@RudelNudel This should be fixed with [v1.0.2](https://github.com/tylercamp/palcalc/releases/tag/v1.0.2), please confirm

**Comment by RudelNudel** [comment]
@tylercamp  The newest release is missing the zip for the program :/

**Comment by tylercamp** [comment]
@RudelNudel Oh whoops, it's up now

**Comment by RudelNudel** [comment]
@tylercamp it's fixed now. runs without problems again. Thank you
