### ISSUE TITLE
Take in consideration legend pals for Legend passive skill

### ISSUE THREAD

**Issue by diogo7santiago** [tylercamp/palcalc#13]
"Legend is a Passive Skill exclusive to All Legendary Pals.
Legendary Pals can be encountered and caught as Level 50 Alpha Field Bosses.
You can teach Legend to other Pals by passing down this skill to an Offspring Pal via Breeding"
According to: https://game8.co/games/Palworld/archives/442373
"The Legend Passive Skill can only be obtained by capturing the following Pals:
Paladius
Necromus
Frostallion
Frostallion Noct
Jetragon"
According to: https://palworld.fandom.com/wiki/Passive_Skills#Legend

So it would be nice if the breeding could start with one of these to pass on Legend.

**Comment by tylercamp** [comment]
If you already have pals with the Legend trait then those will be used as part of the breeding path, but currently it assumes that all wild pals will have random traits.

At the least, the solver should check for "guaranteed traits" specific to each pal, and include those on wild pals.

Do you know if a child legendary pal is also guaranteed to have the "Legend" trait? E.g. does Jetragon _always_ have Legend, or is it possible to breed one without Legend?

**Comment by tylercamp** [comment]
A comment on Palworld discord suggests this it's possible to e.g. breed a Jetragon without Legend, so I'm going to assume this is just for wild pals

**Comment by tylercamp** [comment]
Update applied to [v1.3.0](https://github.com/tylercamp/palcalc/releases/tag/v1.3.0), @diogo7santiago please confirm the fix

(Handles _all_ guaranteed traits, not just Legend)

**Comment by diogo7santiago** [comment]
It is working, thank you!
Is it possible to also add compatibility with Alpha pals?
According to Steam update v0.2.4.0 patch notes:
・Breeding eggs now have a slight chance to produce an Alpha Pal

Alpha pals list (when you catch one it is guaranteed they are alpha and they pass it down)
https://palworld.wiki.gg/wiki/Alpha_Pals

**Comment by tylercamp** [comment]
@diogo7santiago Can do, can you open another issue for that with this info?

**Comment by diogo7santiago** [comment]
Yes, closed this one.
