### ISSUE TITLE
hi tyler, can you update the palworld traits with the new ones?

### ISSUE THREAD

**Issue by tazgameplays** [tylercamp/palcalc#18]
hi tyler, can you update the palworld traits with the new ones? here its a unique place that i found passives ID ! thanks

**Comment by tylercamp** [comment]
Which traits are you referring to? All of the trait IDs in Pal Calc are from this spreadsheet: https://docs.google.com/spreadsheets/d/1YgPc11dgdBUC8jXNp01b7gI6jNHoBRQGwrY_V6lXMgQ/edit?pli=1&gid=517703310#gid=517703310

Since I didn't scrape the traits myself I'll need to find another source for any extra IDs

**Comment by tazgameplays** [comment]
im refering about passive ID's, now have nocturnal , filantropic, etc.. i want the new ones..
![asdasghgh](https://github.com/tylercamp/palcalc/assets/140841320/d0dfcab0-e96e-4e55-8ff6-1074ae1f6040)

**Comment by tylercamp** [comment]
@tazgameplays If you have a save file with pals which have those traits I can try to add those in manually, though there's an issue atm with reading save files with the Sakurajima update

**Comment by KAubuchon76** [comment]
First off thanks @tylercamp for your hard work on palcalc, its a great palworld utility.

I am hoping someone else following this issue has a savefile with all the new passives, unfortunately I do not have them all yet.

If this helps at all, here are the new passives that were added yesterday:
`Philanthropist, Impatient, Infinite Stamina, Noble, Nocturnal`

And I believe these are all of the new Pals:
`Selyne #113, Croajiro #114, Lullu #115, Shroomer #116, Kikit #117, Sootseer #118, Prixter #119, Knocklem #120, Yakumo #121, Dogen #122, Dazemu #123, Mimog #124, Xenovader #125, Xenogard #126`

And the new Pal variants:
`Gorirat Terra #49B, Chillet Ignis #55B, Bushi Noct #72B, Katress Ignis #75B, Wixen Noct #76B, Quivern Botan #95B, Blazamut Ryu #96B, Helzephyr Lux #97B, Menasting Terra #99B, Shroomer Noct #116B`

**Comment by KAubuchon76** [comment]
Looks like there may be a few more than what were initially reported by some sites:
`Easygoing, Eternal Flame, Fine Furs, Fit as a Fiddle, Infinite Stamina, Noble, Nocturnal, Otherworldly, Philanthropist, Shabby, Sickly`

**Comment by tazgameplays** [comment]
good, any way to get id of them?

**Comment by tylercamp** [comment]
> some way to get ID of them?

That's the key question and an outstanding problem as part of #6

I've tried extracting the Palworld assets but didn't have any luck getting usable data. It might be possible to make a mod which reads this data at runtime and writes to a file, but I haven't really looked into that approach yet

**Comment by alt1noreply** [comment]
Just wanted to say thank you for making this tool. Very easy to use and incredibly helpful. Hope you're able to get it updated and working with the latest content drop soon.

**Comment by tylercamp** [comment]
@alt1noreply This should be fixed in [v1.4.3](https://github.com/tylercamp/palcalc/releases/tag/v1.4.3)

**Comment by Jutakl** [comment]
Hopping in to say I love this calculator which I just installed, it's extremely helpful. You're a genius for programming it. I also look forward to the new traits being added because some of them are considered the best of the best for several pal configurations. Nocturnal or Serenity as examples.

**Comment by tylercamp** [comment]
Thank you! A lot of effort went into this and I'm glad to see it being used. I've got some sample saves from others on Reddit and am planning to make an update later today

**Comment by SipeP** [comment]
Hi,
This might help with the new passives:
https://github.com/KrisCris/Palworld-Pal-Editor/blob/develop/src/palworld_pal_editor/assets/data/pal_passives.json

**Comment by tylercamp** [comment]
@SipeP Nice find! I'll take a closer look at this later but this is hopefully everything we need

**Comment by tazgameplays** [comment]
@tylercamp my bro can you add this new passives here??https://github.com/tylercamp/palcalc/blob/f69279ac3f1074aec1edaac024cac1c767d590b1/PalCalc.GenDB/ref/traits.csv#L359

or create a tab in the doc with all... i follow the doc for my edits XDDDDDD
if yes thank you.

**Comment by SipeP** [comment]
@tazgameplays what kind of edits are you talking about?

**Comment by tazgameplays** [comment]
@SipeP i do many edits in pals in my server, skills , passives, for do events, with pals as reward..
so all my players look foward to new events with pals with nocturnal and new passives..
and i list all passives in these link [palcalc/PalCalc.GenDB/ref/traits.csv](https://github.com/tylercamp/palcalc/blob/f69279ac3f1074aec1edaac024cac1c767d590b1/PalCalc.GenDB/ref/traits.csv#L359) cuz it i asked if possible the tylercamp update with new passives there XDD if not do it in doc.

**Comment by SipeP** [comment]
@tazgameplays Why not use something like [Palworld Pal Editor](https://www.nexusmods.com/palworld/mods/995) instead?

**Comment by tazgameplays** [comment]
ahhhhh i never used this mods, i can test, which of these is the best for edit ? i use the palguard exportpals, edit and givepal_j !!

**Comment by tylercamp** [comment]
Was planning to get this done today but I completely reworked the data scraping process and had some unrelated stuff some up earlier, where I'm now writing this at 11pm.

I've got scraping for paldb.cc done and all the latest pals + traits + icons fetched, but I need to do some testing + checks to make sure everything else synced (e.g. pals exclusive to breeding, special breeding combos)

Should have an update ready tomorrow

**Comment by SipeP** [comment]
@tazgameplays Actually I have no experience with any of these mods, as I don't have any need for them. So I cannot give any recommendation and you have to test them yourself :(  

@tylercamp Just out of curiosity, what is paldb.cc being used for? I don't see ID's there, so is it just for Icons, descriptions etc?

**Comment by tylercamp** [comment]
@SipeP its being used to fetch everything needed; it turns out the passive IDs were stored as part of the links

**Comment by tylercamp** [comment]
![Screenshot 2024-07-06 112942](https://github.com/tylercamp/palcalc/assets/3388513/5cd98ad1-35d7-42b6-8774-cbcde40b0105)

**Comment by SipeP** [comment]
That's awesome! Nice find ;) I appreciate all the hard work that you and other Palworld fans (like the creator of paldb.cc) do, I wish I had enough knowledge to help out :(

**Comment by tazgameplays** [comment]
@tylercamp wonderful what you doing, i will use alot the doc with passive ids now, very thanks..
if you could update the gender odds with bellaoir chance.. it will be a good subject for my youtube video and marketing for you doc !! thanks my bro, if have someone we can do for help here we are
![image](https://github.com/tylercamp/palcalc/assets/140841320/a5166161-2931-48c2-a0e5-d326a342d29f)

**Comment by tylercamp** [comment]
@tazgameplays while it's nice that those files could be used for reference by others, their intent was just for Papa Calc to build its internal database. The new scraper will emit all data as JSON, not the CSVs you currently see.

I can make a quick script which outputs all of the scraped data as CSVs, but I won't be doing any additional processing of them. E.g. for gender probabilities the new CSVs would list all probabilities, not just for pals which aren't 50/50

**Comment by tylercamp** [comment]
@tazgameplays @SipeP @alt1noreply @Jutakl @KAubuchon76 The latest pals and traits have been included in [v1.4.4](https://github.com/tylercamp/palcalc/releases/tag/v1.4.4). I'll close this issue, and for any other missing or incorrect pals/traits, please open a new issue.

@tazgameplays A new set of CSVs are available here: https://github.com/tylercamp/palcalc/tree/main/ScrapeData/out/csv

**Comment by tazgameplays** [comment]
hi tyler , sry open you post again , but you have new csv of new passive id? thanks

**Comment by tylercamp** [comment]
@tazgameplays I've uploaded pal and passive skill data again here, but haven't uploaded the other CSVs I had before, let me know if you need them

https://github.com/tylercamp/palcalc/tree/main/PalCalc.GenDB/out-csv

**Comment by tazgameplays** [comment]
very thanks my lorddd ! thats will be very useful ❤️


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Tyler Camp ***@***.***>
Enviado: sábado, 11 de janeiro de 2025 13:22
Para: tylercamp/palcalc ***@***.***>
Cc: tazgameplays ***@***.***>; Mention ***@***.***>
Assunto: Re: [tylercamp/palcalc] hi tyler, can you update the palworld traits with the new ones? (Issue #18)


@tazgameplays<https://github.com/tazgameplays> I've uploaded pal and passive skill data again here, but haven't uploaded the other CSVs I had before, let me know if you need them

https://github.com/tylercamp/palcalc/tree/main/PalCalc.GenDB/out-csv

**Comment by tazgameplays** [comment]
@tylercamp you passives csv are being very useful for me, very very thanks.
i have another question, if possible..
palworld have many npc's that we can use in base and i have some events about it for the community.. 
you can create a list of all npc's and your id's if possible?
will be very useful for i give npc's in prize of events.

**Comment by tylercamp** [comment]
@tazgameplays Please open new issues with requests, rather than commenting on closed issues
