### ISSUE TITLE
Claims save file was not yet cached and throws and errors out after a few moments

### ISSUE THREAD

**Issue by Pokenar** [tylercamp/palcalc#25]
This happened after the most recent update. The crashlog mentions the new pals and skills as unknown, so I'm wondering if the new update that fixed a save-related bug caused the program to be unable to read save files saved in the new update?

**Comment by Jutakl** [comment]
Yes, I am unable to run this program now that the new update, which modified save files, has been installed. Noooo! I really wanted to recalculate some breeding trees now that I caught a bunch of new pals.

The specific error that pops up after Loading Save File:

An error occurred when loading the safe file.
Please find the generated ZIP file to send with any support questions:
<Path of CRASHLOG.zip>

**Comment by tylercamp** [comment]
Will take a look, does the previous v1.4.4 version still work?

**Comment by tylercamp** [comment]
Should be fixed in v1.4.6 release, please confirm

**Comment by Pokenar** [comment]
The new update has indeed solved the crash.
