### ISSUE TITLE
Save file inspector

### ISSUE THREAD

**Issue by tylercamp** [tylercamp/palcalc#27]
Add a new window which allows you to directly view the list of containers and their pals with search features

(Helpful for users, helpful for debugging container detection issues)

- Show parsed pal info
- Show raw GVAS pal info
- Have "Inspect" and "Search" tabs
  - Inspect
    - Simple list of containers, flex-list of contents, show all details of container + pals
  - Search
    - Use grid matching the location type, allow customizing grid size, show tabs of container contents
    - Search by single pal and/or multiple traits
    - Search preview would fade out containers + tabs which don't have matching pal

**Comment by Fusionette** [comment]
Any way to edit the save data would be amazing for those of us who play on a server and don't have access to the save file -- my current solution is a bit involved:

- I created a local game called "Pal Cache" and left it with zero pals, making sure to never touch it again.
- I then manually edit the cache/saves/.json file for that game and manually add my pals to the OwnedPals array.

PalCalc doesn't try to rebuild the cache and happily uses the data I provided, so it is **a** solution... but it's not very user-friendly.

**Comment by tylercamp** [comment]
@Fusionette could you make a new issue for this? It might be appropriate to add that feature within this "inspector" window but it would still be a new / unrelated feature

**Comment by tylercamp** [comment]
Save inspector added to [v1.5.0](https://github.com/tylercamp/palcalc/releases/tag/v1.5.0)

<img width="661" alt="save inspector" src="https://github.com/user-attachments/assets/7335ca56-450b-44c8-8906-222408ca7fee">

**Comment by tylercamp** [comment]
@Fusionette FYI manual editor tracked in #58 and merged pending release in v1.8.0
