### ISSUE TITLE
Wild pal gender probabilities

### ISSUE THREAD

**Issue by tylercamp** [tylercamp/palcalc#3]
Are wild pal gender probabilities always 50/50? Do they match the [gender breeding probabilities](https://palworld.fandom.com/wiki/Breeding#Gender_Ratios)? Or is it a separate set of probabilities?

**Comment by RudelNudel** [comment]
Several Pals have different ratio of male to female. Can be found on  i.e. https://paldb.cc/en/Lovander under stats. There is male probality listed.
At first glance it seems to match the gender breeding probabilities. I guess it is the same probalitiy for breeding as for wild pals.

**Comment by tylercamp** [comment]
The gender probabilities _are_ currently used for breeding estimates, but I'm wondering if that same probability is applied for wild pals as well. Could probably check by looking for Lovander spawns and track frequency of each gender

**Comment by tylercamp** [comment]
Judging from people having a hard time catching male Bellanoirs, it's likely that this same probability is used for wild pals, so I'll go with that assumption

**Comment by tylercamp** [comment]
Applied with [v1.3.0](https://github.com/tylercamp/palcalc/releases/tag/v1.3.0)
