### ISSUE TITLE
Show icons for pal gender instead of text

### ISSUE THREAD

**Issue by tylercamp** [tylercamp/palcalc#33]

**Comment by YupGoolg** [comment]
We just created it for you.

![any](https://github.com/tylercamp/palcalc/assets/96374741/2a936431-a2a9-46ad-b20a-6e85e77143a5)
![female](https://github.com/tylercamp/palcalc/assets/96374741/e404e445-28ef-4502-a4d3-8136bd656392)
![male](https://github.com/tylercamp/palcalc/assets/96374741/a0e1c5e6-7814-4b94-86e6-0d440867e934)
![opposite](https://github.com/tylercamp/palcalc/assets/96374741/99f4075d-3a65-4b14-9e4e-693310627c3d)

**Comment by tylercamp** [comment]
@YupGoolg Nice, thanks! Could you make the arrows on the last one white, since the breeding tree uses a dark background?

**Comment by YupGoolg** [comment]
sure :)
[
![opposite_w](https://github.com/user-attachments/assets/6004f857-cfa3-4323-8da0-24c574db64aa)
](url)

**Comment by tylercamp** [comment]
uhhhhhh where'd their comments go lol

I didn't keep a copy of the icons they gave so 🤷

**Comment by tylercamp** [comment]
Using material icons, released in 1.9.0
