### ISSUE TITLE
Recognized as a virus?

### ISSUE THREAD

**Issue by YupGoolg** [tylercamp/palcalc#34]
When uploading a file built in Nexus mode, it is recognized as a virus.

![스크린샷 2024-07-12 192744](https://github.com/user-attachments/assets/44ea54ff-e6c7-491d-81de-a401ea2f1f40)

https://www.nexusmods.com/palworld/mods/1676

**Comment by tylercamp** [comment]
Yeah there are false-positives, if you look at the VirusTotal results there are a few scanners which show viruses but the rest show as clean

There's a stickied post in the nexusmods listing of my app

You'll need to contact nexusmods support to get an exemption

**Comment by YupGoolg** [comment]
aha. ok:)
