### ISSUE TITLE
Can a child pal be bred with zero of the parents traits?

### ISSUE THREAD

**Issue by tylercamp** [tylercamp/palcalc#5]
The [breeding trait calculation](https://www.reddit.com/r/Palworld/comments/1af9in7/passive_skill_inheritance_mechanics_in_breeding/) suggests that, if either of the parents have any traits, the child pal will always inherit at least one of those traits.

Is this actually true? Are there any counterexamples?

**Comment by Fusionette** [comment]
I have never had a child that doesn't inherit at least **one** trait, out of hundreds of eggs. I've had it inherit just the one trait and up to three random skills, but the first trait has always been from one of the parents. Not conclusive proof, but if it happens it is **very** rare.
