### ISSUE TITLE
Crashes on load of save. 

### ISSUE THREAD

**Issue by curanthir-1** [tylercamp/palcalc#52]
always crashes on load of save. Version 1.7.3, Steam.  Also sometimes crashes the game while it's running, would be nice to allow manual save selection and loading. Crashlog linked
[CRASHLOG.zip](https://github.com/user-attachments/files/16402092/CRASHLOG.zip)

**Comment by tylercamp** [comment]
> Also sometimes crashes the game while it's running

@curanthir-1 It causes _Palworld_ to crash?

**Comment by tylercamp** [comment]
@curanthir-1 The startup crash is caused by duplicate files in the `Players` sub-folder of your save folder, e.g. `Players/00000000000000000000000000000001 - Copy.sav`

**Comment by curanthir-1** [comment]
Yes, happened while playing local multiplayer as the host

**Comment by curanthir-1** [comment]
deleted duplicate saves, and it works now. Havent seen crash palworld again, but haven't been hosting local multiplayer

**Comment by curanthir-1** [comment]
have not seen it crash again recently, cant replicate. May have been one off bug combined with the duplicate save issue
