### ISSUE TITLE
error during startup 

### ISSUE THREAD

**Issue by Kiddos19882** [tylercamp/palcalc#54]
[log20240918.txt](https://github.com/user-attachments/files/17036441/log20240918.txt)

**Comment by tylercamp** [comment]
Seems to be the same as this problem: https://github.com/cheahjs/palworld-save-tools/issues/187

**Comment by tylercamp** [comment]
Should be fixed with [v1.7.4](https://github.com/tylercamp/palcalc/releases/tag/v1.7.4)

**Comment by Kiddos19882** [comment]
[log20240919.txt](https://github.com/user-attachments/files/17052274/log20240919.txt)
![Screenshot_1](https://github.com/user-attachments/assets/d8c1e398-959b-40b0-8a74-fa70ca718012)

The error also occurs on version 1.7.4.

**Comment by tylercamp** [comment]
@Kiddos19882 [Try this version](https://github.com/user-attachments/files/17052333/PalCalc.UI_2.exe.zip), will post as new release after confirmation

**Comment by Kiddos19882** [comment]
Everything is working now, thank you!
![изображение](https://github.com/user-attachments/assets/0fe181c0-319f-476a-b199-209924381099)

**Comment by tylercamp** [comment]
Released as [v1.7.5](https://github.com/tylercamp/palcalc/releases/tag/v1.7.5)
