### ISSUE TITLE
Error during start up- Bug

### ISSUE THREAD

**Issue by jokers-ace** [tylercamp/palcalc#55]
[CRASHLOG.zip](https://github.com/user-attachments/files/17045379/CRASHLOG.zip)

Have tried:
Reinstalling
Using older version from nexus mods
running in admin

Doesnt let me select anything within the application before popping up 3 error messages and then closing

![image](https://github.com/user-attachments/assets/700a4530-b34e-4ecc-9b91-391af48cc105)

**Comment by tylercamp** [comment]
Likely the same as #54, though the logs weren't properly stored in that ZIP for some reason

**Comment by tylercamp** [comment]
Should be fixed with [v1.7.4](https://github.com/tylercamp/palcalc/releases/tag/v1.7.4)
