### ISSUE TITLE
Ability to denote gender of target pal

### ISSUE THREAD

**Issue by TheManInPlaid** [tylercamp/palcalc#61]
As a creature comfort QoL, it'd be nice to be able to specify gender of the target pal along with the passives. Run into a few occasions where I need a pal with X,Y,Z passives of a certain gender but the calc says I have it because I have one as the other gender.

Example: 
Have Female Lamball with Work Slave, Artisan, Serious, Nocturnal
Need Male Lamball with No passives
Calc returns my Female Lamball with No passives when I try to calculate a breeding tree.

... if this already exists, let me know, I could just be blind.

**Comment by tylercamp** [comment]
This can be added, but I suspect that you're wanting a specific gender for use in breeding

In that case I'd suggest you just use pal calc to directly get the final result you want rather than trying to come up with an intermediate pal

**Comment by tylercamp** [comment]
Pal calc should still be offering multiple ways to get to that pal with zero traits, though the first result would just be a pal you already own

Is it only giving you the one result without giving other options?

**Comment by TheManInPlaid** [comment]
Yup, you're correct. Just the pal I already have. Granted, 95% of the time this isn't an issue, just is a pita the other 5% when I'm looking for something specific for IV breeding/mass producing more on one. 

![image](https://github.com/user-attachments/assets/a70deefd-5bbc-48d8-a9dc-b20d2af8079b)
![image](https://github.com/user-attachments/assets/a801b113-fe5a-416e-bf30-317a642780de)

**Comment by tylercamp** [comment]
Are the other listed options from your screenshot not viable? I'm confused about which part is a PITA since it gives other options

**Comment by TheManInPlaid** [comment]
Ah, I was trying to stay within my lamball example from earlier. Beside this very particular example, this works like a charm.

Basically the long and short of it is I want to make more of the four passives pal but want to get a male with no passives to do it. However, since I already have a female with no passives, trying to get a breeding line for a male just brings up the female.

**Comment by tylercamp** [comment]
I'm referring to the list of options at the bottom right, in your lamball screenshots there are multiple breeding options

**Comment by tylercamp** [comment]
You can pick the second option in the list for the fastest way to properly breed a lamball, and you'd just keep breeding until you got a male with those traits

**Comment by TheManInPlaid** [comment]
Ahh, sorry, it's been a _painfully_ long day. Yeah, those do work and that's what I have been doing. At I lead with at the beginning, very much a small creature comfort but thought I'd at least offer up the suggestion.

**Comment by tylercamp** [comment]
@TheManInPlaid Is the annoying bit just that you need to reselect the 2nd option whenever you click on that entry? Would it suffice to just remember which one was selected?

**Comment by TheManInPlaid** [comment]
Yeah that would work as well if it remembered the previous selection.

**Comment by tylercamp** [comment]
Added in https://github.com/tylercamp/palcalc/commit/1b0a725e1dc8e041ae58dbf1b1d933c8c3c72943 and released in [v1.9.0](https://github.com/tylercamp/palcalc/releases/tag/v1.9.0)
