### ISSUE TITLE
Account for breeding time reduction from "Philanthropist"

### ISSUE THREAD

**Issue by tonyctalope** [tylercamp/palcalc#65]
I think that the 'Philanthropist' trait reduction is not taken into account in the software; it could be nice if it were.

**Comment by tylercamp** [comment]
@tonyctalope What behavior are you seeing, specifically? What version of Pal Calc are you using?

For me Philanthropist appears in the list of available passives, it's picked recognized by the Save Inspector, and solving for a pal with Philanthropist works just fine

(Though I needed to go through a few different saves to find one which had pals with that passive)

Are you sure your save file has pals with the Philanthropist passive? Does it show up in the Save Inspector? (Click the "Inspect" button when your save is selected)

**Comment by tonyctalope** [comment]
I was referring to the Philanthropist trait's bonus of +100% breed speed. It doesn’t seem to be factored into the breed speed calculations in Pal Calc ?

**Comment by tylercamp** [comment]
@tonyctalope Ah I see, I thought you meant it wasn't being recognized as a passive, I honestly hadn't actually known about that effect

I agree this should be taken into account, do you know how the passive stacks? E.g. what's the breeding speed if 1 parent has it vs. both parents?

**Comment by tonyctalope** [comment]
I currently don't know, but I'll do some tests (it doesn’t look complicated) and let you know ASAP.

**Comment by tonyctalope** [comment]
I just tested a 25% breed:
- Without: 75s
- With 1 Philanthropist parent: 37.5s
- With 2 Philanthropist parents: 25s

For 100%, this translates to:
- Without: 5m
- With 1 parent: 2m30
- With 2 parents: 1m40

I also have this video that supports my tests: https://www.youtube.com/watch?v=39l5rO_NxPs

**Comment by tylercamp** [comment]
I'll plan to address this in v1.10.0, along with IV solving

**Comment by tylercamp** [comment]
Note: In addition to affecting breeding times for children, the solver should also consider children which inherit the Philanthropist passive, even if it's not intended for the final pal

**Comment by tylercamp** [comment]
> Note: In addition to affecting breeding times for children, the solver should also consider children which inherit the Philanthropist passive, even if it's not intended for the final pal

Will leave this out for now - you can get this behavior by just adding Philanthropist as an Optional passive, which will allow it to be included as a target passive for children
