### ISSUE TITLE
I think some of the breeding combinations changed

### ISSUE THREAD

**Issue by dedren** [tylercamp/palcalc#73]
According to Palcalc breeding Surfent and Pyrin Noct was supposed to give Sweepa, but instead it is now giving Azurmane.

**Comment by tylercamp** [comment]
@dedren This is a known issue and will be fixed in Pal Calc 1.10.1, hopefully releasing late today or end of tomorrow

**Comment by tylercamp** [comment]
Fixed with v1.10.1
