### ISSUE TITLE
Errors When Loading Feybreak Save FIle

### ISSUE THREAD

**Issue by RevanFan1** [tylercamp/palcalc#75]
![image](https://github.com/user-attachments/assets/9ea8ae56-e7c7-458d-af74-62fffc42f955)

These errors pop up every time I launch PalCalc using the recently released version. I removed any saves from before Feybreak, so the only save it is detecting is my Feybreak save. When I close the error messages and manually select the save, I can't run any pal calculations, nor can I inspect the save. I also can't save presets.

Attached is the exported save file, and the crash log zip is at the link below.

https://send.vis.ee/download/2169cd9a29ad4bf9/#S5pkheDVLlW6gF4r_8MlWw

[Palworld-76561198007981053-0FE0CCF34A3DC486FB074E9DB48BFFB4.zip](https://github.com/user-attachments/files/18245024/Palworld-76561198007981053-0FE0CCF34A3DC486FB074E9DB48BFFB4.zip)

**Comment by tylercamp** [comment]
Looks like this is caused by some unexpected data related to the randomizer. Quick fix, will release in 1.10.2 in an hour or two

**Comment by tylercamp** [comment]
@RevanFan1 v1.10.2 has been released

**Comment by RevanFan1** [comment]
Everything is working perfectly now and my antivirus is also no longer freaking out. Thanks for the update!

One final request. Could you change breeding time (minutes) into seconds? I use a mod that changes the breeding time to 90 seconds, which can't be properly represented with just a whole number of minutes.

**Comment by tylercamp** [comment]
Can do, but should make a new issue to track that

Very low priority since it just affects the times that are displayed, I'd rather bundle it with some other changes in the next release instead of making a whole version just for that
