### ISSUE TITLE
Crashlog

### ISSUE THREAD

**Issue by Thanatos100** [tylercamp/palcalc#79]
Hello, i'm getting this crash in bouth my old and new playthrough. apparently it cant load the saves.
[CRASHLOG.zip](https://github.com/user-attachments/files/18268008/CRASHLOG.zip)

**Comment by tylercamp** [comment]
@Thanatos100 It looks like this is loading an older save file from before Feybreak, can you confirm that this save has been loaded in Palworld with the Feybreak update at least once? They Feybreak update included a breaking change in the save file format and newer versions of Pal Calc will fail on the older save file format

Try [v1.10.0](https://github.com/tylercamp/palcalc/releases/tag/v1.10.0) which supports the older format

**Comment by tylercamp** [comment]
I just noticed from looking at your logs - its seems you're using Pal Calc v1.4.4, which was released several months ago

Definitely try v1.10.0, that should fix the issue

**Comment by Thanatos100** [comment]
I downloaded the latest version on nexus and now this one you sugested, still nothing. The old save started working now.  but im not playing on that anymore. And know the crashlog is 78mb.

**Comment by Thanatos100** [comment]
I downloaded the newest version from the nexus website and it didn't work. And discovered that the game need to be closed, then it will work. Nice.
